language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_install:
  - sudo apt-get install -qq libxml2-dev


before_script:
  - composer install

script:
  - mkdir -p build/coverage
  - phpunit --coverage-clover build/coverage/clover.xml
